import navBarBug from "../../Images/navbar-bug.jpg";
import footerBug from "../../Images/footer-bug.jpg";
export const BUGS = [
  {
    title: "Navbar",
    url: navBarBug,
    alt: "bug associated with navbar",
    description: [
      "<p>Header.view is created with View Tools</p>",
      "<p>Within Header.view is a div titled <strong>HeaderContainer</strong>. Nested within HeaderContainer are two child divs, <i>Icon</i> and <i>AppName</i>.</p>",
      "<p><strong>When:</strong> Header.view.js is autogenerated</p>",
      "<p><strong>Expected:</strong> both divs <i>Icon</i> and <i>AppName</i> are properly nested within HeaderContainer</p>",
      "<p><strong>Actual:</strong> div <i>AppName</i> is inserted inside the YouRock svg, as if the svg were a HOC.</p>"
    ],
    hotfix:
      "For the time being, I have modified the jsx in Header.view.js manually to ensure the Header properly renders."
  },
  {
    title: "Footer",
    url: footerBug,
    alt: "bug associated with footer text",
    description: [
      "<p>Footer.view is created with View Tools</p>",
      "<p>Footer.view contains three nested divs in <i>TextField</i>. They are <i>Author</i>, <i>Github</i>, and <i>LinkedIn</i></p>",
      "<p><strong>When:</strong> Footer.view.js is autogenerated</p>",
      "<p><strong>Expected:</strong> all three nested divs are autogenerated</p>",
      "<p><strong>Actual:</strong>Only the first nested div is created, i.e. <i>Author</i></p>"
    ],
    hotfix: "None was done so that you could see the issue for yourselves"
  }
];
