export const BUGS = [
  {
    title: "Navbar",
    url: "../../Images/navbar-bug.png",
    description: [
      "Within Header.view is a div title HeaderContainer. Nested within HeaderContainer are two child divs, Icon and AppName",
      "When: Header.view.js is autogenerated",
      "Expect: both div Icon and AppName are properly nested within HeaderContainer",
      "Actual: div AppName is inserted inside the YouRock svg, as if the svg were a HOC."
    ],
    hotfix:
      "For the time being, I have modified the jsx in Header.view.js manually to ensure the Header properly renders."
  }
];
